"""update time and change column name

Revision ID: 1871a5563743
Revises: 0b33fb1330ac
Create Date: 2019-03-16 21:22:18.485953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1871a5563743'
down_revision = '0b33fb1330ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('snow_updates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timeStamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_snow_updates_timeStamp'), 'snow_updates', ['timeStamp'], unique=False)
    op.add_column('conditions', sa.Column('forcastDate', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_conditions_forcastDate'), 'conditions', ['forcastDate'], unique=False)
    op.drop_index('ix_conditions_timestamp', table_name='conditions')
    op.drop_column('conditions', 'timestamp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conditions', sa.Column('timestamp', sa.DATETIME(), nullable=True))
    op.create_index('ix_conditions_timestamp', 'conditions', ['timestamp'], unique=False)
    op.drop_index(op.f('ix_conditions_forcastDate'), table_name='conditions')
    op.drop_column('conditions', 'forcastDate')
    op.drop_index(op.f('ix_snow_updates_timeStamp'), table_name='snow_updates')
    op.drop_table('snow_updates')
    # ### end Alembic commands ###
