"""changes to table

Revision ID: 4779f91b0028
Revises: 9e4f79c25906
Create Date: 2019-02-26 18:46:26.434044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4779f91b0028'
down_revision = '9e4f79c25906'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_post_timestamp'), 'post', ['timestamp'], unique=False)
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.create_foreign_key(None, 'post', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.create_foreign_key(None, 'post', 'user', ['timestamp'], ['id'])
    op.drop_index(op.f('ix_post_timestamp'), table_name='post')
    op.drop_column('post', 'user_id')
    # ### end Alembic commands ###
